version: "3.8"
name: kittygram

services:
  postgres:
    image: postgres:13.10
    env:
        POSTGRES_USER: django_user
        POSTGRES_PASSWORD: django_password
        POSTGRES_DB: django_db
        ports:
          - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: pashkami/kittygram_backend:latest
    env_file: .env
    ports: 
      - "9000:9000"
    volumes:
      - static:/backend_static
      - media:/backend/media
    depends_on:
      - postgres

  frontend:
    image: pashkami/kittygram_frontend:latest
    env_file: .env
    volumes:
      - static:/app/build

  gateway:
    image: pashkami/kittygram_gateway:latest
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media

volumes:
  static:
  media:
  pg_data: