name: 'kittygram'

services:
  gateway:
    image: pashkami/kittygram_gateway:latest
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/var/html/backend/backend_static
      - media:/var/html/media
      - static:/var/html//frontend-static

  backend:
    image: pashkami/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - postgres
    
  frontend:
    image: pashkami/kittygram_frontend:latest
    volumes:
      - static:/app/build/frontend_static
    
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
volumes:
  pg_data:
  static:
  media:

  