volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: pashkami/backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: pashkami/frontend
    env_file: .env
    volumes:
      - static:/frontend_static

  gateway:
    image: pashkami/gateway
    env_file: .env
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - static:/staticfiles
      - media:/app/media