name: 'kittygram'

services:
  gateway:
    image: pashkami/kittygram_gateway:latest
    ports:
      - '80:80'
    depends_on:
      - kittygram_backend
      - kittygram_frontend
    volumes:
      - backend-static:/var/html/backend
      - media:/var/html/media
      - frontend-static:/var/html/static

  backend:
    image: pashkami/kittygram_backend:latest
    env_file: .env

    volumes:
      - backend-static:/app/collected_static
      - media:/app/media
    depends_on:
      - postgres
    
  frontend:
    image: pashkami/kittygram_frontend:latest
    volumes:
      - frontend-static:/app/build
    
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
volumes:
  pg_data:
  static:
  media:

  